- hosts: localhost
  become: true
  tasks:
    - name: Install zsh
      apt: name=zsh
    - name: Change shell
      shell: chsh -s `which zsh`
    - name: Install ohmyzsh
      shell: curl -L https://raw.github.com/robbyrussel/oh-my-zsh/master/tools/install.sh | sh
    - name: Install the zsh plugin autosuggestions
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
        dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
    - name: update our zshrc
      shell: sed -i 's/git/(git zsh-autosuggestions' ~/.zshrc
